Fixing signal handling, verbosity detection

diff --git a/bin/remote b/bin/remote
--- a/bin/remote
+++ b/bin/remote
@@ -3,6 +3,22 @@ me=`which $0`
 prog_name=`basename $0`
 source `dirname $me`/remote-common
 
+random_num=$((1 + RANDOM % 1000))
+cmd_file_name=.remote_cmd_${random_num}.sh
+
+trap cleanup SIGHUP SIGINT SIGTERM
+
+cleanup()
+{
+  if [ -f $cmd_file_name ]; then
+    rm -f $cmd_file_name
+  fi
+  #delegating to common cleanup
+  common_cleanup
+  #redundant exit but just to be safe
+  exit
+}
+
 usage() {
   echo "Usage: $1 [-vneh] <command>"
   echo " -v: verbose"
@@ -50,8 +66,6 @@ local_dir=`get_local_directory`
 remote_host=`get_remote_host`
 remote_dir=`get_remote_directory`
 remote_command_dir=`get_remote_command_directory`
-random_num=$((1 + RANDOM % 1000))
-cmd_file_name=.remote_cmd_${random_num}.sh
 
 generate_command $command_flag $cmd_file_name $remote_dir $remote_command_dir "$@"
 ensure_synced $verbosity_flag $dry_run_flag
@@ -61,6 +75,8 @@ then
 else
   ssh -Kq $remote_host "cd $remote_command_dir; REMOTE_HOST_INDEX=$REMOTE_HOST_INDEX ./$cmd_file_name" 2>&1 | tee /tmp/$remote_host.log
 fi
-#cleanup local cmd file
-rm -f $cmd_file_name
-ensure_synced -r $verbosity_flag $dry_run_flag
+if [ $? -eq "0" ]; then
+  # reverse sync only if the command was successful
+  ensure_synced -r $verbosity_flag $dry_run_flag
+fi
+cleanup
